HOSTS:
  debian-8-x64:
    platform: debian-8-amd64
    image: debian:8
    hypervisor: docker
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y wget locales-all puppet git'
      - 'rm -f /usr/sbin/policy-rc.d'

CONFIG:
  type: foss
  #log_level: verbose
  #log_level: debug

ssh:
  password: root
  auth_methods: ["password"]
